
IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name='vital')
	EXEC('CREATE SCHEMA vital')
GO



IF OBJECT_ID('vital.births', 'U') IS NOT NULL
	DROP TABLE vital.births;
CREATE TABLE vital.births (
	id INT IDENTITY(1,1),		--	1
	CONSTRAINT vital_births_id PRIMARY KEY CLUSTERED (id ASC),
	state_file_number VARCHAR(10),
	void_flag VARCHAR(1),	--	INT,
	name_last VARCHAR(21),
	name_suffix VARCHAR(4),
	name_first VARCHAR(16),
	name_middle VARCHAR(16),
	sex VARCHAR(1),
	date_of_birth VARCHAR(8),	--DATE,
	time_of_birth VARCHAR(4),	--	INT,
	fac_type_code INT,
	fac_nv_code VARCHAR(4),	--	INT,
	fac_st_nv_old INT,
	fac_city_nv_old VARCHAR(3),	--	INT,
	fac_cnty_nv_old INT,
	attendant_title_code INT,
	mother_name_last VARCHAR(21),
	mother_name_suffix VARCHAR(4),
	mother_name_first VARCHAR(16),
	mother_name_middle VARCHAR(16),
	mother_name_last_p VARCHAR(21),
	mother_name_suffix_p VARCHAR(4),
	b2_mother_dob VARCHAR(8),	--	DATE,
	b2_mother_age INT,
	mbir_country_country_code_nv INT,
	mbir_state_state_code_nv INT,
	mres_state_state_code_nv INT,
	mother_res_city_nv_old VARCHAR(3),	--	INT,
	mother_res_cnty_nv_old VARCHAR(2),	--	INT,
	mother_res_addr1 VARCHAR(40),
	mother_res_apt VARCHAR(10),
	mother_res_zip VARCHAR(9),
	mother_res_incity INT,
	b2_mother_ed INT,
	mother_occupation_cd VARCHAR(3),	--INT,
	mother_industry_cd INT,
	mother_ssn VARCHAR(9),
	father_name_last VARCHAR(21),
	father_name_suffix VARCHAR(4),
	father_name_first VARCHAR(16),
	father_name_middle VARCHAR(16),
	b2_father_dob VARCHAR(8),	--	DATE,
	b2_father_age INT,
	fbir_country_country_code_nv INT,
	fbir_state_state_code_nv INT,
	b2_father_ed INT,
	father_occupation_cd VARCHAR(3),	--	INT,
	father_industry_cd INT,
	father_ssn VARCHAR(9),
	b2_mother_ever_married INT,
	mother_married VARCHAR(1),	--	INT,
	father_is_husband VARCHAR(1),	--	INT,
	father_sign_pat_affidavit VARCHAR(1),	--	INT,
	b2_trans_mother INT,
	menses_date VARCHAR(8),	--	DATE,
	b2_prenatal_yesno INT,
	b2_prenatal_date_begin VARCHAR(8),	--	DATE,
	b2_prenatal_date_end VARCHAR(8),	--	DATE,
	b2_prenat_tot_visits INT,
	b2_mother_height_feet INT,
	b2_mother_height_inch INT,
	b2_mother_pre_preg_wt INT,
	b2_mother_wt_at_deliv INT,
	live_births_total INT,
	live_births_date_mmyyyy VARCHAR(6),
	live_births_living INT,
	live_births_dead VARCHAR(2),	--	INT,
	term_number INT,
	term_date_mmyyyy VARCHAR(6),
	b2_tobacco_use VARCHAR(1),	--	INT,
	b2_mother_cig_or_pack VARCHAR(1),	--	INT,
	b2_mother_cig_prev INT,
	b2_mother_cig_prev_pack VARCHAR(2),	--	INT,
	b2_mother_cig_first_tri INT,
	b2_mother_cig_first_pack VARCHAR(2),	--	INT,
	b2_mother_cig_second_tri INT,
	b2_mother_cig_second_pack VARCHAR(2),	--	INT,
	b2_mother_cig_last_tri INT,
	b2_mother_cig_last_pack VARCHAR(2),	--	INT,
	m_alcohol_use INT,
	m_alcohol_drink_week VARCHAR(2),	--	INT,
	m_drug_use INT,
	m_drug_prescription INT,
	m_drug_otc INT,
	m_drug_other INT,
	m_drug_other_lit VARCHAR(30),
	m_mr_none INT,
	m_mr_diab INT,
	m_mr_diab_gest INT,
	m_mr_hypert_all INT,
	m_mr_hypert_chronic INT,
	m_mr_hypert_preg INT,
	m_mr_eclampsia INT,
	m_mr_prev_preterm INT,
	m_mr_prev_poor_outcome INT,
	m_mr_preg_from_treatment INT,
	m_mr_infert_drugs INT,
	m_mr_assist_rep_tech INT,
	m_mr_prev_cesarean_yesno INT,
	m_mr_prev_ces_numb INT,
	m_mr_anemia INT,
	m_mr_cardiac INT,
	m_mr_lung_disease INT,
	m_mr_hydraminos_olig INT,
	m_mr_hemoglobinopathy INT,
	m_mr_incompent_cervix INT,
	m_mr_prev_4000_plus INT,
	m_mr_renal_disease INT,
	m_mr_rh_sensit INT,
	m_mr_uterine_bleeding INT,
	m_mr_other INT,
	m_mr_other_lit VARCHAR(30),
	unknown01 VARCHAR(1),
	m_inf_none INT,
	m_inf_gonorrhea INT,
	m_inf_syphilis INT,
	m_inf_chlamydia INT,
	m_inf_hepatitis_b INT,
	m_inf_hepatitis_c INT,
	m_inf_hpv INT,
	m_inf_hiv_aids INT,
	m_inf_cmv INT,
	m_inf_rubella INT,
	m_inf_toxoplasmosis INT,
	m_inf_genital_herpes INT,
	m_inf_tuberculosis INT,
	m_inf_other INT,
	m_inf_other_lit VARCHAR(30),
	unknown02 VARCHAR(1),
	m_ob_none INT,
	m_ob_cerclage INT,
	m_ob_tocolysis INT,
	m_ob_amnio INT,
	m_ob_fetal_monitor INT,
	m_ob_cephalic_success INT,
	m_ob_cephalic_failed INT,
	m_ob_ultrasound INT,
	m_ob_other INT,
	m_ob_other_lit VARCHAR(30),
	unknown03 VARCHAR(1),
	m_ol_none INT,
	m_ol_premature_rom INT,
	m_ol_precip_labor INT,
	m_ol_prolong_labor INT,
	m_cld_none INT,
	m_cld_induction INT,
	m_cld_augment INT,
	m_cld_non_vertex INT,
	m_cld_steroid INT,
	m_cld_antibiotic INT,
	m_cld_chorioamnio INT,
	m_cld_meconium INT,
	m_cld_fetal_intolerance INT,
	m_cld_epidural INT,
	m_cld_febrile INT,
	m_cld_abr_placenta INT,
	m_cld_placenta_previa INT,
	m_cld_bleeding INT,
	m_cld_seizures INT,
	m_cld_dysfunctional INT,
	m_cld_cephalopelvic INT,
	m_cld_cord_prolapse INT,
	m_cld_anesthetic INT,
	m_cld_other INT,
	m_cld_other_lit VARCHAR(30),
	unknown04 VARCHAR(1),
	m_md_forceps_attempt INT,
	m_md_vacuum_attempt INT,
	b2_birpresent_code INT,
	b2_birroute_code INT,
	m_md_ces_labor_attempt VARCHAR(1),	--	INT,
	unknown05 VARCHAR(1),
	m_mm_none INT,
	m_mm_transfusion INT,
	m_mm_perineal_lacerat INT,
	m_mm_ruptured_uterus INT,
	m_mm_hysterectomy INT,
	m_mm_icu INT,
	m_mm_or_proc INT,
	m_mm_unknown INT,
	apgar_5 INT,
	apgar_10 INT,
	birth_weight_unit VARCHAR(1),	--	INT,
	birth_weight_grams INT,
	birth_weight_lbs INT,
	birth_weight_oz INT,
	gestation_weeks INT,
	plurality INT,
	birth_order INT,
	b2_born_alive INT,
	b2_match_number VARCHAR(6),
	trans_infant INT,
	b2_infant_living INT,
	m_ac_none INT,
	m_ac_vent_less_30 INT,
	m_ac_vent_more_30 INT,
	m_ac_nicu INT,
	m_ac_surfactant INT,
	m_ac_antibiotic_sepsis INT,
	m_ac_seizures INT,
	m_ac_anemia INT,
	m_ac_fas INT,
	m_ac_hyaline INT,
	m_ac_meconium_as INT,
	m_ac_birth_injury INT,
	m_ac_other INT,
	m_ac_other_lit VARCHAR(30),
	unknown06 VARCHAR(1),
	m_anom_none INT,
	m_anom_anencep INT,
	m_anom_spina INT,
	m_anom_micro INT,
	m_anom_nervous INT,
	m_anom_nervous_lit VARCHAR(30),
	m_anom_heart INT,
	m_anom_heart_malform INT,
	m_anom_circ INT,
	m_anom_circ_lit VARCHAR(30),
	m_anom_omphal INT,
	m_anom_gastroschisis INT,
	m_anom_rectal INT,
	m_anom_tracheo INT,
	m_anom_gastro INT,
	m_anom_gastro_lit VARCHAR(30),
	m_anom_limb_reduct INT,
	m_anom_cleft_lip INT,
	m_anom_cleft_palate INT,
	m_anom_polydact INT,
	m_anom_club_foot INT,
	m_anom_diaph_hernia INT,
	m_anom_muscle INT,
	m_anom_muscle_lit VARCHAR(30),
	m_anom_malf_genitalia INT,
	m_anom_renal INT,
	m_anom_hypospadias INT,
	m_anom_urogenital INT,
	m_anom_urogenital_lit VARCHAR(30),
	m_anom_downs_code VARCHAR(1),	--	INT,
	m_anom_cdit INT,
	m_anom_chrom_other INT,
	m_anom_chrom_lit VARCHAR(30),
	m_anom_other INT,
	m_anom_other_lit VARCHAR(30),
	certifiertitleid INT,
	certifier_date_comp VARCHAR(8),	--	DATE,
	registrar_regis_date VARCHAR(8),	--	DATE,
	b2_mother_wic_yesno INT,
	b2_source_pay_code INT,
	m_breastfeeding INT,
	ssn_requested INT,
	hos_number VARCHAR(20),
	m_mother_med_rec_num VARCHAR(20),
	b2_hosp_paternity_complete VARCHAR(1),	--	INT,
	b2_mother_ethnic_yesno VARCHAR(1),	--	INT,
	b2_mother_mexican VARCHAR(1),	--	INT,
	b2_mother_pr VARCHAR(1),	--	INT,
	b2_mother_cuban VARCHAR(1),	--	INT,
	b2_mother_ethnic_other VARCHAR(1),	--	INT,
	b2_mother_ethnic VARCHAR(20),
	b2_mother_race_white INT,
	b2_mother_race_black INT,
	b2_mother_race_am_indian INT,
	b2_mother_race_am_ind_lit VARCHAR(30),
	b2_mother_race_asian_ind INT,
	b2_mother_race_asian_oth INT,
	b2_mother_race_asian_lit VARCHAR(30),
	b2_mother_race_chinese INT,
	b2_mother_race_filipino INT,
	b2_mother_race_japanese INT,
	b2_mother_race_korean INT,
	b2_mother_race_vietnamese INT,
	b2_mother_race_hawaiian INT,
	b2_mother_race_guam INT,
	b2_mother_race_samoan INT,
	b2_mother_race_pac_other INT,
	b2_mother_race_pac_lit VARCHAR(30),
	b2_mother_race_other INT,
	b2_mother_race_other_lit VARCHAR(30),
	b2_mother_race_unknown INT,
	b2_mother_race_refused INT,
	b2_mrace1e VARCHAR(3),
	b2_mrace2e VARCHAR(3),
	b2_mrace3e VARCHAR(3),
	b2_mrace4e VARCHAR(3),
	b2_mrace5e VARCHAR(3),
	b2_mrace6e VARCHAR(3),
	b2_mrace7e VARCHAR(3),
	b2_mrace8e VARCHAR(3),
	b2_mrace16e VARCHAR(3),
	unknown07 VARCHAR(3),
	b2_mrace18e VARCHAR(3),
	unknown08 VARCHAR(3),
	b2_mrace20e VARCHAR(3),
	unknown09 VARCHAR(3),
	b2_mrace22e VARCHAR(3),
	unknown10 VARCHAR(3),
	b2_nchs_mo_ethnic_cd VARCHAR(3),
	b2_nchs_mo_ethnic_lit_cd VARCHAR(3),
	b2_mo_bridged_race INT,
	b2_father_ethnic_yesno VARCHAR(1),	--	INT,
	b2_father_mexican VARCHAR(1),	--	INT,
	b2_father_pr VARCHAR(1),	--	INT,
	b2_father_cuban VARCHAR(1),	--	INT,
	b2_father_ethnic_other VARCHAR(1),	--	INT,
	b2_father_ethnic VARCHAR(20),
	b2_father_race_white INT,
	b2_father_race_black INT,
	b2_father_race_am_indian INT,
	b2_father_race_am_ind_lit VARCHAR(30),
	b2_father_race_asian_ind INT,
	b2_father_race_asian_oth INT,
	b2_father_race_asian_lit VARCHAR(30),
	b2_father_race_chinese INT,
	b2_father_race_filipino INT,
	b2_father_race_japanese INT,
	b2_father_race_korean INT,
	b2_father_race_vietnamese INT,
	b2_father_race_hawaiian INT,
	b2_father_race_guam INT,
	b2_father_race_samoan INT,
	b2_father_race_pac INT,
	b2_father_race_pac_lit VARCHAR(30),
	b2_father_race_other INT,
	b2_father_race_other_lit VARCHAR(30),
	b2_father_race_unknown INT,
	b2_father_race_refused INT,
	b2_frace1e VARCHAR(3),
	b2_frace2e VARCHAR(3),
	b2_frace3e VARCHAR(3),
	b2_frace4e VARCHAR(3),
	b2_frace5e VARCHAR(3),
	b2_frace6e VARCHAR(3),
	b2_frace7e VARCHAR(3),
	b2_frace8e VARCHAR(3),
	b2_frace16e VARCHAR(3),
	unknown11 VARCHAR(3),
	b2_frace18e VARCHAR(3),
	unknown12 VARCHAR(3),
	b2_frace20e VARCHAR(3),
	unknown13 VARCHAR(3),
	b2_frace22e VARCHAR(3),
	unknown14 VARCHAR(3),
	b2_nchs_fa_ethnic_cd VARCHAR(3),
	b2_nchs_fa_ethnic_lit_cd VARCHAR(3),
	b2_fa_bridged_race INT,
	event_year INT,
	isactive VARCHAR(1),	--	INT,
	unknown15 VARCHAR(15),
	mother_birth_state VARCHAR(2),
	mother_birth_country_fips VARCHAR(2),
	unknown16 VARCHAR(1),
	mother_res_city_fips VARCHAR(5),
	unknown17 VARCHAR(1),
	mother_res_cnty_fips VARCHAR(3),
	unknown18 VARCHAR(1),
	mother_res_state VARCHAR(2),
	unknown19 VARCHAR(1),
	mother_res_country_fips VARCHAR(2),
	unknown20 VARCHAR(4),
	ssn_child VARCHAR(9),
	unknown21 VARCHAR(12),
	death_matched VARCHAR(1),	--	INT,
	death_state_file_number VARCHAR(10),
	death_date VARCHAR(8),	--	DATE,
	fbir_state_fips_alpha_cd VARCHAR(2),
	father_birth_country_fips VARCHAR(2),
	reg_type_code VARCHAR(20),




	source_filename VARCHAR(255),

	--	Sadly, BULK INSERT does NOT preserve file order so this is moot.
	--	If remove, remove code that RESEED ID
	--	Actually, despite saying it doesn't, it seems to preserve the order.
	source_record_number INT,

	imported_at DATETIME
		CONSTRAINT vital_births_imported_at_default
		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	imported_to_observations BIT
		CONSTRAINT vital_births_imported_to_observations_default
		DEFAULT 'FALSE' NOT NULL,
);
GO





IF OBJECT_ID('vital.births_buffer', 'U') IS NOT NULL
	DROP TABLE vital.births_buffer;
CREATE TABLE vital.births_buffer (
	state_file_number VARCHAR(10),
	void_flag VARCHAR(1),	--	INT,
	name_last VARCHAR(21),
	name_suffix VARCHAR(4),
	name_first VARCHAR(16),
	name_middle VARCHAR(16),
	sex VARCHAR(1),
	date_of_birth VARCHAR(8),	--	DATE,
	time_of_birth VARCHAR(4),	--	INT,
	fac_type_code INT,
	fac_nv_code VARCHAR(4),	--	INT,
	fac_st_nv_old INT,
	fac_city_nv_old VARCHAR(3),	--	INT,
	fac_cnty_nv_old INT,
	attendant_title_code INT,
	mother_name_last VARCHAR(21),
	mother_name_suffix VARCHAR(4),
	mother_name_first VARCHAR(16),
	mother_name_middle VARCHAR(16),
	mother_name_last_p VARCHAR(21),
	mother_name_suffix_p VARCHAR(4),
	b2_mother_dob VARCHAR(8),	--	DATE,
	b2_mother_age INT,
	mbir_country_country_code_nv INT,
	mbir_state_state_code_nv INT,
	mres_state_state_code_nv INT,
	mother_res_city_nv_old VARCHAR(3),	--	INT,
	mother_res_cnty_nv_old VARCHAR(2),	--	INT,
	mother_res_addr1 VARCHAR(40),
	mother_res_apt VARCHAR(10),
	mother_res_zip VARCHAR(9),
	mother_res_incity INT,
	b2_mother_ed INT,
	mother_occupation_cd VARCHAR(3),	--INT,
	mother_industry_cd INT,
	mother_ssn VARCHAR(9),
	father_name_last VARCHAR(21),
	father_name_suffix VARCHAR(4),
	father_name_first VARCHAR(16),
	father_name_middle VARCHAR(16),
	b2_father_dob VARCHAR(8),	--	DATE,
	b2_father_age INT,
	fbir_country_country_code_nv INT,
	fbir_state_state_code_nv INT,
	b2_father_ed INT,
	father_occupation_cd VARCHAR(3),	--	INT,
	father_industry_cd INT,
	father_ssn VARCHAR(9),
	b2_mother_ever_married INT,
	mother_married VARCHAR(1),	--	INT,
	father_is_husband VARCHAR(1),	--	INT,
	father_sign_pat_affidavit VARCHAR(1),	--	INT,
	b2_trans_mother INT,
	menses_date VARCHAR(8),	--	DATE,
	b2_prenatal_yesno INT,
	b2_prenatal_date_begin VARCHAR(8),	--	DATE,
	b2_prenatal_date_end VARCHAR(8),	--	DATE,
	b2_prenat_tot_visits INT,
	b2_mother_height_feet INT,
	b2_mother_height_inch INT,
	b2_mother_pre_preg_wt INT,
	b2_mother_wt_at_deliv INT,
	live_births_total INT,
	live_births_date_mmyyyy VARCHAR(6),
	live_births_living INT,
	live_births_dead VARCHAR(2),	--	INT,
	term_number INT,
	term_date_mmyyyy VARCHAR(6),
	b2_tobacco_use VARCHAR(1),	--	INT,
	b2_mother_cig_or_pack VARCHAR(1),	--	INT,
	b2_mother_cig_prev INT,
	b2_mother_cig_prev_pack VARCHAR(2),	--	INT,
	b2_mother_cig_first_tri INT,
	b2_mother_cig_first_pack VARCHAR(2),	--	INT,
	b2_mother_cig_second_tri INT,
	b2_mother_cig_second_pack VARCHAR(2),	--	INT,
	b2_mother_cig_last_tri INT,
	b2_mother_cig_last_pack VARCHAR(2),	--	INT,
	m_alcohol_use INT,
	m_alcohol_drink_week VARCHAR(2),	--	INT,
	m_drug_use INT,
	m_drug_prescription INT,
	m_drug_otc INT,
	m_drug_other INT,
	m_drug_other_lit VARCHAR(30),
	m_mr_none INT,
	m_mr_diab INT,
	m_mr_diab_gest INT,
	m_mr_hypert_all INT,
	m_mr_hypert_chronic INT,
	m_mr_hypert_preg INT,
	m_mr_eclampsia INT,
	m_mr_prev_preterm INT,
	m_mr_prev_poor_outcome INT,
	m_mr_preg_from_treatment INT,
	m_mr_infert_drugs INT,
	m_mr_assist_rep_tech INT,
	m_mr_prev_cesarean_yesno INT,
	m_mr_prev_ces_numb INT,
	m_mr_anemia INT,
	m_mr_cardiac INT,
	m_mr_lung_disease INT,
	m_mr_hydraminos_olig INT,
	m_mr_hemoglobinopathy INT,
	m_mr_incompent_cervix INT,
	m_mr_prev_4000_plus INT,
	m_mr_renal_disease INT,
	m_mr_rh_sensit INT,
	m_mr_uterine_bleeding INT,
	m_mr_other INT,
	m_mr_other_lit VARCHAR(30),
	unknown01 VARCHAR(1),
	m_inf_none INT,
	m_inf_gonorrhea INT,
	m_inf_syphilis INT,
	m_inf_chlamydia INT,
	m_inf_hepatitis_b INT,
	m_inf_hepatitis_c INT,
	m_inf_hpv INT,
	m_inf_hiv_aids INT,
	m_inf_cmv INT,
	m_inf_rubella INT,
	m_inf_toxoplasmosis INT,
	m_inf_genital_herpes INT,
	m_inf_tuberculosis INT,
	m_inf_other INT,
	m_inf_other_lit VARCHAR(30),
	unknown02 VARCHAR(1),
	m_ob_none INT,
	m_ob_cerclage INT,
	m_ob_tocolysis INT,
	m_ob_amnio INT,
	m_ob_fetal_monitor INT,
	m_ob_cephalic_success INT,
	m_ob_cephalic_failed INT,
	m_ob_ultrasound INT,
	m_ob_other INT,
	m_ob_other_lit VARCHAR(30),
	unknown03 VARCHAR(1),
	m_ol_none INT,
	m_ol_premature_rom INT,
	m_ol_precip_labor INT,
	m_ol_prolong_labor INT,
	m_cld_none INT,
	m_cld_induction INT,
	m_cld_augment INT,
	m_cld_non_vertex INT,
	m_cld_steroid INT,
	m_cld_antibiotic INT,
	m_cld_chorioamnio INT,
	m_cld_meconium INT,
	m_cld_fetal_intolerance INT,
	m_cld_epidural INT,
	m_cld_febrile INT,
	m_cld_abr_placenta INT,
	m_cld_placenta_previa INT,
	m_cld_bleeding INT,
	m_cld_seizures INT,
	m_cld_dysfunctional INT,
	m_cld_cephalopelvic INT,
	m_cld_cord_prolapse INT,
	m_cld_anesthetic INT,
	m_cld_other INT,
	m_cld_other_lit VARCHAR(30),
	unknown04 VARCHAR(1),
	m_md_forceps_attempt INT,
	m_md_vacuum_attempt INT,
	b2_birpresent_code INT,
	b2_birroute_code INT,
	m_md_ces_labor_attempt VARCHAR(1),	--	INT,
	unknown05 VARCHAR(1),
	m_mm_none INT,
	m_mm_transfusion INT,
	m_mm_perineal_lacerat INT,
	m_mm_ruptured_uterus INT,
	m_mm_hysterectomy INT,
	m_mm_icu INT,
	m_mm_or_proc INT,
	m_mm_unknown INT,
	apgar_5 INT,
	apgar_10 INT,
	birth_weight_unit VARCHAR(1),	--	INT,
	birth_weight_grams INT,
	birth_weight_lbs INT,
	birth_weight_oz INT,
	gestation_weeks INT,
	plurality INT,
	birth_order INT,
	b2_born_alive INT,
	b2_match_number VARCHAR(6),
	trans_infant INT,
	b2_infant_living INT,
	m_ac_none INT,
	m_ac_vent_less_30 INT,
	m_ac_vent_more_30 INT,
	m_ac_nicu INT,
	m_ac_surfactant INT,
	m_ac_antibiotic_sepsis INT,
	m_ac_seizures INT,
	m_ac_anemia INT,
	m_ac_fas INT,
	m_ac_hyaline INT,
	m_ac_meconium_as INT,
	m_ac_birth_injury INT,
	m_ac_other INT,
	m_ac_other_lit VARCHAR(30),
	unknown06 VARCHAR(1),
	m_anom_none INT,
	m_anom_anencep INT,
	m_anom_spina INT,
	m_anom_micro INT,
	m_anom_nervous INT,
	m_anom_nervous_lit VARCHAR(30),
	m_anom_heart INT,
	m_anom_heart_malform INT,
	m_anom_circ INT,
	m_anom_circ_lit VARCHAR(30),
	m_anom_omphal INT,
	m_anom_gastroschisis INT,
	m_anom_rectal INT,
	m_anom_tracheo INT,
	m_anom_gastro INT,
	m_anom_gastro_lit VARCHAR(30),
	m_anom_limb_reduct INT,
	m_anom_cleft_lip INT,
	m_anom_cleft_palate INT,
	m_anom_polydact INT,
	m_anom_club_foot INT,
	m_anom_diaph_hernia INT,
	m_anom_muscle INT,
	m_anom_muscle_lit VARCHAR(30),
	m_anom_malf_genitalia INT,
	m_anom_renal INT,
	m_anom_hypospadias INT,
	m_anom_urogenital INT,
	m_anom_urogenital_lit VARCHAR(30),
	m_anom_downs_code VARCHAR(1),	--	INT,
	m_anom_cdit INT,
	m_anom_chrom_other INT,
	m_anom_chrom_lit VARCHAR(30),
	m_anom_other INT,
	m_anom_other_lit VARCHAR(30),
	certifiertitleid INT,
	certifier_date_comp VARCHAR(8),	--	DATE,
	registrar_regis_date VARCHAR(8),	--	DATE,
	b2_mother_wic_yesno INT,
	b2_source_pay_code INT,
	m_breastfeeding INT,
	ssn_requested INT,
	hos_number VARCHAR(20),
	m_mother_med_rec_num VARCHAR(20),
	b2_hosp_paternity_complete VARCHAR(1),	--	INT,
	b2_mother_ethnic_yesno VARCHAR(1),	--	INT,
	b2_mother_mexican VARCHAR(1),	--	INT,
	b2_mother_pr VARCHAR(1),	--	INT,
	b2_mother_cuban VARCHAR(1),	--	INT,
	b2_mother_ethnic_other VARCHAR(1),	--	INT,
	b2_mother_ethnic VARCHAR(20),
	b2_mother_race_white INT,
	b2_mother_race_black INT,
	b2_mother_race_am_indian INT,
	b2_mother_race_am_ind_lit VARCHAR(30),
	b2_mother_race_asian_ind INT,
	b2_mother_race_asian_oth INT,
	b2_mother_race_asian_lit VARCHAR(30),
	b2_mother_race_chinese INT,
	b2_mother_race_filipino INT,
	b2_mother_race_japanese INT,
	b2_mother_race_korean INT,
	b2_mother_race_vietnamese INT,
	b2_mother_race_hawaiian INT,
	b2_mother_race_guam INT,
	b2_mother_race_samoan INT,
	b2_mother_race_pac_other INT,
	b2_mother_race_pac_lit VARCHAR(30),
	b2_mother_race_other INT,
	b2_mother_race_other_lit VARCHAR(30),
	b2_mother_race_unknown INT,
	b2_mother_race_refused INT,
	b2_mrace1e VARCHAR(3),
	b2_mrace2e VARCHAR(3),
	b2_mrace3e VARCHAR(3),
	b2_mrace4e VARCHAR(3),
	b2_mrace5e VARCHAR(3),
	b2_mrace6e VARCHAR(3),
	b2_mrace7e VARCHAR(3),
	b2_mrace8e VARCHAR(3),
	b2_mrace16e VARCHAR(3),
	unknown07 VARCHAR(3),
	b2_mrace18e VARCHAR(3),
	unknown08 VARCHAR(3),
	b2_mrace20e VARCHAR(3),
	unknown09 VARCHAR(3),
	b2_mrace22e VARCHAR(3),
	unknown10 VARCHAR(3),
	b2_nchs_mo_ethnic_cd VARCHAR(3),
	b2_nchs_mo_ethnic_lit_cd VARCHAR(3),
	b2_mo_bridged_race INT,
	b2_father_ethnic_yesno VARCHAR(1),	--	INT,
	b2_father_mexican VARCHAR(1),	--	INT,
	b2_father_pr VARCHAR(1),	--	INT,
	b2_father_cuban VARCHAR(1),	--	INT,
	b2_father_ethnic_other VARCHAR(1),	--	INT,
	b2_father_ethnic VARCHAR(20),
	b2_father_race_white INT,
	b2_father_race_black INT,
	b2_father_race_am_indian INT,
	b2_father_race_am_ind_lit VARCHAR(30),
	b2_father_race_asian_ind INT,
	b2_father_race_asian_oth INT,
	b2_father_race_asian_lit VARCHAR(30),
	b2_father_race_chinese INT,
	b2_father_race_filipino INT,
	b2_father_race_japanese INT,
	b2_father_race_korean INT,
	b2_father_race_vietnamese INT,
	b2_father_race_hawaiian INT,
	b2_father_race_guam INT,
	b2_father_race_samoan INT,
	b2_father_race_pac INT,
	b2_father_race_pac_lit VARCHAR(30),
	b2_father_race_other INT,
	b2_father_race_other_lit VARCHAR(30),
	b2_father_race_unknown INT,
	b2_father_race_refused INT,
	b2_frace1e VARCHAR(3),
	b2_frace2e VARCHAR(3),
	b2_frace3e VARCHAR(3),
	b2_frace4e VARCHAR(3),
	b2_frace5e VARCHAR(3),
	b2_frace6e VARCHAR(3),
	b2_frace7e VARCHAR(3),
	b2_frace8e VARCHAR(3),
	b2_frace16e VARCHAR(3),
	unknown11 VARCHAR(3),
	b2_frace18e VARCHAR(3),
	unknown12 VARCHAR(3),
	b2_frace20e VARCHAR(3),
	unknown13 VARCHAR(3),
	b2_frace22e VARCHAR(3),
	unknown14 VARCHAR(3),
	b2_nchs_fa_ethnic_cd VARCHAR(3),
	b2_nchs_fa_ethnic_lit_cd VARCHAR(3),
	b2_fa_bridged_race INT,
	event_year INT,
	isactive VARCHAR(1),	--	INT,
	unknown15 VARCHAR(15),
	mother_birth_state VARCHAR(2),
	mother_birth_country_fips VARCHAR(2),
	unknown16 VARCHAR(1),
	mother_res_city_fips VARCHAR(5),
	unknown17 VARCHAR(1),
	mother_res_cnty_fips VARCHAR(3),
	unknown18 VARCHAR(1),
	mother_res_state VARCHAR(2),
	unknown19 VARCHAR(1),
	mother_res_country_fips VARCHAR(2),
	unknown20 VARCHAR(4),
	ssn_child VARCHAR(9),
	unknown21 VARCHAR(12),
	death_matched VARCHAR(1),	--	INT,
	death_state_file_number VARCHAR(10),
	death_date VARCHAR(8),	--	DATE,
	fbir_state_fips_alpha_cd VARCHAR(2),
	father_birth_country_fips VARCHAR(2),
	reg_type_code VARCHAR(20),

	source_filename VARCHAR(255),

	--	Sadly, BULK INSERT does NOT preserve file order so this is moot.
	--	If remove, remove code that RESEED ID
	--	Actually, despite saying it doesn't, it seems to preserve the order.
	source_record_number INT IDENTITY(1,1),

	imported_at DATETIME
		CONSTRAINT vital_births_buffer_imported_at_default
		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	imported_to_observations BIT
		CONSTRAINT vital_births_buffer_imported_to_observations_default
		DEFAULT 'FALSE' NOT NULL
);
GO



IF OBJECT_ID ( 'vital.bulk_insert_births', 'V' ) IS NOT NULL
	DROP VIEW vital.bulk_insert_births;
GO
-- This is ugly as there are 366 fields.  Nevertheless.
CREATE VIEW vital.bulk_insert_births AS SELECT
	state_file_number,
	void_flag,
	name_last,
	name_suffix,
	name_first,
	name_middle,
	sex,
	date_of_birth,
	time_of_birth,
	fac_type_code,
	fac_nv_code,
	fac_st_nv_old,
	fac_city_nv_old,
	fac_cnty_nv_old,
	attendant_title_code,
	mother_name_last,
	mother_name_suffix,
	mother_name_first,
	mother_name_middle,
	mother_name_last_p,
	mother_name_suffix_p,
	b2_mother_dob,
	b2_mother_age,
	mbir_country_country_code_nv,
	mbir_state_state_code_nv,
	mres_state_state_code_nv,
	mother_res_city_nv_old,
	mother_res_cnty_nv_old,
	mother_res_addr1,
	mother_res_apt,
	mother_res_zip,
	mother_res_incity,
	b2_mother_ed,
	mother_occupation_cd,
	mother_industry_cd,
	mother_ssn,
	father_name_last,
	father_name_suffix,
	father_name_first,
	father_name_middle,
	b2_father_dob,
	b2_father_age,
	fbir_country_country_code_nv,
	fbir_state_state_code_nv,
	b2_father_ed,
	father_occupation_cd,
	father_industry_cd,
	father_ssn,
	b2_mother_ever_married,
	mother_married,
	father_is_husband,
	father_sign_pat_affidavit,
	b2_trans_mother,
	menses_date,
	b2_prenatal_yesno,
	b2_prenatal_date_begin,
	b2_prenatal_date_end,
	b2_prenat_tot_visits,
	b2_mother_height_feet,
	b2_mother_height_inch,
	b2_mother_pre_preg_wt,
	b2_mother_wt_at_deliv,
	live_births_total,
	live_births_date_mmyyyy,
	live_births_living,
	live_births_dead,
	term_number,
	term_date_mmyyyy,
	b2_tobacco_use,
	b2_mother_cig_or_pack,
	b2_mother_cig_prev,
	b2_mother_cig_prev_pack,
	b2_mother_cig_first_tri,
	b2_mother_cig_first_pack,
	b2_mother_cig_second_tri,
	b2_mother_cig_second_pack,
	b2_mother_cig_last_tri,
	b2_mother_cig_last_pack,
	m_alcohol_use,
	m_alcohol_drink_week,
	m_drug_use,
	m_drug_prescription,
	m_drug_otc,
	m_drug_other,
	m_drug_other_lit,
	m_mr_none,
	m_mr_diab,
	m_mr_diab_gest,
	m_mr_hypert_all,
	m_mr_hypert_chronic,
	m_mr_hypert_preg,
	m_mr_eclampsia,
	m_mr_prev_preterm,
	m_mr_prev_poor_outcome,
	m_mr_preg_from_treatment,
	m_mr_infert_drugs,
	m_mr_assist_rep_tech,
	m_mr_prev_cesarean_yesno,
	m_mr_prev_ces_numb,
	m_mr_anemia,
	m_mr_cardiac,
	m_mr_lung_disease,
	m_mr_hydraminos_olig,
	m_mr_hemoglobinopathy,
	m_mr_incompent_cervix,
	m_mr_prev_4000_plus,
	m_mr_renal_disease,
	m_mr_rh_sensit,
	m_mr_uterine_bleeding,
	m_mr_other,
	m_mr_other_lit,
	unknown01,
	m_inf_none,
	m_inf_gonorrhea,
	m_inf_syphilis,
	m_inf_chlamydia,
	m_inf_hepatitis_b,
	m_inf_hepatitis_c,
	m_inf_hpv,
	m_inf_hiv_aids,
	m_inf_cmv,
	m_inf_rubella,
	m_inf_toxoplasmosis,
	m_inf_genital_herpes,
	m_inf_tuberculosis,
	m_inf_other,
	m_inf_other_lit,
	unknown02,
	m_ob_none,
	m_ob_cerclage,
	m_ob_tocolysis,
	m_ob_amnio,
	m_ob_fetal_monitor,
	m_ob_cephalic_success,
	m_ob_cephalic_failed,
	m_ob_ultrasound,
	m_ob_other,
	m_ob_other_lit,
	unknown03,
	m_ol_none,
	m_ol_premature_rom,
	m_ol_precip_labor,
	m_ol_prolong_labor,
	m_cld_none,
	m_cld_induction,
	m_cld_augment,
	m_cld_non_vertex,
	m_cld_steroid,
	m_cld_antibiotic,
	m_cld_chorioamnio,
	m_cld_meconium,
	m_cld_fetal_intolerance,
	m_cld_epidural,
	m_cld_febrile,
	m_cld_abr_placenta,
	m_cld_placenta_previa,
	m_cld_bleeding,
	m_cld_seizures,
	m_cld_dysfunctional,
	m_cld_cephalopelvic,
	m_cld_cord_prolapse,
	m_cld_anesthetic,
	m_cld_other,
	m_cld_other_lit,
	unknown04,
	m_md_forceps_attempt,
	m_md_vacuum_attempt,
	b2_birpresent_code,
	b2_birroute_code,
	m_md_ces_labor_attempt,
	unknown05,
	m_mm_none,
	m_mm_transfusion,
	m_mm_perineal_lacerat,
	m_mm_ruptured_uterus,
	m_mm_hysterectomy,
	m_mm_icu,
	m_mm_or_proc,
	m_mm_unknown,
	apgar_5,
	apgar_10,
	birth_weight_unit,
	birth_weight_grams,
	birth_weight_lbs,
	birth_weight_oz,
	gestation_weeks,
	plurality,
	birth_order,
	b2_born_alive,
	b2_match_number,
	trans_infant,
	b2_infant_living,
	m_ac_none,
	m_ac_vent_less_30,
	m_ac_vent_more_30,
	m_ac_nicu,
	m_ac_surfactant,
	m_ac_antibiotic_sepsis,
	m_ac_seizures,
	m_ac_anemia,
	m_ac_fas,
	m_ac_hyaline,
	m_ac_meconium_as,
	m_ac_birth_injury,
	m_ac_other,
	m_ac_other_lit,
	unknown06,
	m_anom_none,
	m_anom_anencep,
	m_anom_spina,
	m_anom_micro,
	m_anom_nervous,
	m_anom_nervous_lit,
	m_anom_heart,
	m_anom_heart_malform,
	m_anom_circ,
	m_anom_circ_lit,
	m_anom_omphal,
	m_anom_gastroschisis,
	m_anom_rectal,
	m_anom_tracheo,
	m_anom_gastro,
	m_anom_gastro_lit,
	m_anom_limb_reduct,
	m_anom_cleft_lip,
	m_anom_cleft_palate,
	m_anom_polydact,
	m_anom_club_foot,
	m_anom_diaph_hernia,
	m_anom_muscle,
	m_anom_muscle_lit,
	m_anom_malf_genitalia,
	m_anom_renal,
	m_anom_hypospadias,
	m_anom_urogenital,
	m_anom_urogenital_lit,
	m_anom_downs_code,
	m_anom_cdit,
	m_anom_chrom_other,
	m_anom_chrom_lit,
	m_anom_other,
	m_anom_other_lit,
	certifiertitleid,
	certifier_date_comp,
	registrar_regis_date,
	b2_mother_wic_yesno,
	b2_source_pay_code,
	m_breastfeeding,
	ssn_requested,
	hos_number,
	m_mother_med_rec_num,
	b2_hosp_paternity_complete,
	b2_mother_ethnic_yesno,
	b2_mother_mexican,
	b2_mother_pr,
	b2_mother_cuban,
	b2_mother_ethnic_other,
	b2_mother_ethnic,
	b2_mother_race_white,
	b2_mother_race_black,
	b2_mother_race_am_indian,
	b2_mother_race_am_ind_lit,
	b2_mother_race_asian_ind,
	b2_mother_race_asian_oth,
	b2_mother_race_asian_lit,
	b2_mother_race_chinese,
	b2_mother_race_filipino,
	b2_mother_race_japanese,
	b2_mother_race_korean,
	b2_mother_race_vietnamese,
	b2_mother_race_hawaiian,
	b2_mother_race_guam,
	b2_mother_race_samoan,
	b2_mother_race_pac_other,
	b2_mother_race_pac_lit,
	b2_mother_race_other,
	b2_mother_race_other_lit,
	b2_mother_race_unknown,
	b2_mother_race_refused,
	b2_mrace1e,
	b2_mrace2e,
	b2_mrace3e,
	b2_mrace4e,
	b2_mrace5e,
	b2_mrace6e,
	b2_mrace7e,
	b2_mrace8e,
	b2_mrace16e,
	unknown07,
	b2_mrace18e,
	unknown08,
	b2_mrace20e,
	unknown09,
	b2_mrace22e,
	unknown10,
	b2_nchs_mo_ethnic_cd,
	b2_nchs_mo_ethnic_lit_cd,
	b2_mo_bridged_race,
	b2_father_ethnic_yesno,
	b2_father_mexican,
	b2_father_pr,
	b2_father_cuban,
	b2_father_ethnic_other,
	b2_father_ethnic,
	b2_father_race_white,
	b2_father_race_black,
	b2_father_race_am_indian,
	b2_father_race_am_ind_lit,
	b2_father_race_asian_ind,
	b2_father_race_asian_oth,
	b2_father_race_asian_lit,
	b2_father_race_chinese,
	b2_father_race_filipino,
	b2_father_race_japanese,
	b2_father_race_korean,
	b2_father_race_vietnamese,
	b2_father_race_hawaiian,
	b2_father_race_guam,
	b2_father_race_samoan,
	b2_father_race_pac,
	b2_father_race_pac_lit,
	b2_father_race_other,
	b2_father_race_other_lit,
	b2_father_race_unknown,
	b2_father_race_refused,
	b2_frace1e,
	b2_frace2e,
	b2_frace3e,
	b2_frace4e,
	b2_frace5e,
	b2_frace6e,
	b2_frace7e,
	b2_frace8e,
	b2_frace16e,
	unknown11,
	b2_frace18e,
	unknown12,
	b2_frace20e,
	unknown13,
	b2_frace22e,
	unknown14,
	b2_nchs_fa_ethnic_cd,
	b2_nchs_fa_ethnic_lit_cd,
	b2_fa_bridged_race,
	event_year,
	isactive,
	unknown15,
	mother_birth_state,
	mother_birth_country_fips,
	unknown16,
	mother_res_city_fips,
	unknown17,
	mother_res_cnty_fips,
	unknown18,
	mother_res_state,
	unknown19,
	mother_res_country_fips,
	unknown20,
	ssn_child,
	unknown21,
	death_matched,
	death_state_file_number,
	death_date,
	fbir_state_fips_alpha_cd,
	father_birth_country_fips,
	reg_type_code
FROM vital.births_buffer;
GO



IF IndexProperty(Object_Id('vital.births'),
	'vital_births_state_file_number', 'IndexId') IS NOT NULL
	DROP INDEX vital_births_state_file_number
		ON vital.births;
CREATE INDEX vital_births_state_file_number
	ON vital.births( state_file_number );


IF IndexProperty(Object_Id('vital.births'),
	'vital_births__mother_res_zip', 'IndexId') IS NOT NULL
	DROP INDEX vital_births__mother_res_zip
		ON vital.births;
IF COL_LENGTH('vital.births','_mother_res_zip') IS NOT NULL
	ALTER TABLE vital.births DROP COLUMN _mother_res_zip;
ALTER TABLE vital.births ADD _mother_res_zip AS CAST( mother_res_zip AS VARCHAR ) PERSISTED;
CREATE INDEX vital_births__mother_res_zip
	ON vital.births( _mother_res_zip );


